services:
  check24-app:
    container_name: check24-app
    build:
      context: .
      dockerfile: deployment/docker/php/Dockerfile
      target: prod
    restart: unless-stopped
    environment:
      - APP_ENV=prod
    networks:
      - check24-backend

networks:
  check24-backend: