# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.acme_mapping_file: '%env(APP_INSURANCE_ACME_MAPPING_FILE)%'
    app.acme_customer_input_file: '%env(APP_INSURANCE_ACME_SAMPLE_INPUT_FILE)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            # Shared
            App\Shared\Domain\MappingProvider\MappingProviderInterface: '@App\Shared\Infrastructure\MappingProvider\YamlMappingProvider'
            App\Shared\Domain\InputParser\InputParserInterface: '@App\Shared\Infrastructure\InputParser\JsonInputParser'
            #FieldMapping
            App\FieldMapping\Domain\Service\FieldMapperServiceInterface: '@App\FieldMapping\Application\Service\FieldMapperService'
            App\FieldMapping\Domain\Service\FieldValidatorServiceInterface: '@App\FieldMapping\Application\Service\FieldValidatorService'
            App\FieldMapping\Domain\Service\FieldStaticServiceInterface: '@App\FieldMapping\Application\Service\FieldStaticService'
            App\FieldMapping\Domain\Service\FieldMappingServiceInterface: '@App\FieldMapping\Application\Service\FieldMappingService'
            # Insurance
            App\Insurance\Domain\Command\CreateInsuranceRequestCommandInterface: '@App\Insurance\Application\Command\CreateInsuranceRequestCommand'
            App\Insurance\Domain\UseCase\MapInputToXMLRequestUseCaseInterface: '@App\Insurance\Application\UseCase\MapInputToXMLRequestUseCase'

    serializer.encoder.xml:
        class: Symfony\Component\Serializer\Encoder\XmlEncoder
        tags: [ 'serializer.encoder' ]

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Insurance\Presentation\CLI\:
        resource: '../src/Insurance/Presentation/CLI/'
        tags: [ 'console.command' ]

    App\FieldMapping\:
        resource: '../src/FieldMapping/'
        exclude:
            - '../src/FieldMapping/Domain/Exception/'
            - '../src/FieldMapping/Domain/ValueObject/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
